name: Run tests on macOS
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install libelf
        run: brew install libelf
      - name: Run tests
        run: swift test
