name: Run tests on Linux
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install libelf
        run: sudo apt install libelf-dev
      - name: Run tests
        run: swift test
